---

- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Stop services
      shell: |
        cd /mwhome/obi/instances/instance1/bin
        ./opmnctl stopall
        ./opmnctl status
      register: stop_services_result
      ignore_errors: true

    - name: Display Stop services result
      debug:
        msg: "{{ stop_services_result.stdout }}"

    - name: Stop WebLogic
      shell: |
        cd /mwhome/obi/user_projects/domains/bifoundation_domain/bin
        ./stopWebLogic.sh
      register: stop_weblogic_result
      ignore_errors: true

    - name: Display Stop WebLogic result
      debug:
        msg: "{{ stop_weblogic_result.stdout }}"

    - name: Start WebLogic
      shell: |
        cd /mwhome/obi/user_projects/domains/bifoundation_domain/bin
        nohup ./startWebLogic.sh &
        tail -f nohup.out
      register: start_weblogic_result
      ignore_errors: true

    - name: Display Start WebLogic result
      debug:
        msg: "{{ start_weblogic_result.stdout }}"

    - name: Start Services
      shell: |
        cd /mwhome/obi/instances/instance1/bin
        ./opmnctl startall
        ./opmnctl status
      register: start_services_result
      ignore_errors: true

    - name: Display Start Services result
      debug:
        msg: "{{ start_services_result.stdout }}"

