---

- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Stop WebLogic
      command: su - oracle -c /u01/app/oracle/config/domains/mydomain/bin/stopWebLogic.sh
      register: weblogic_result
      ignore_errors: true

    - name: Wait for 30 seconds
      wait_for:
        timeout: 30

    - name: Start WebLogic
      command: su - oracle -c /u01/app/oracle/config/domains/mydomain/bin/startWebLogic.sh
      register: start_result
      ignore_errors: true

    - name: Display WebLogic start result
      debug:
        var: start_result.stdout_lines

    - name: Create apples.txt file
      file:
        path: /u01/app/oracle/config/domains/mydomain/apples.txt
        state: touch
        mode: '0644'

