---

- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Starting Server
      shell: nohup /u01/app/oracle/config/domains/mydomain/bin/startWebLogic.sh > /dev/null 2>&1 &
      args:
        chdir: /u01/app/oracle/config/domains/mydomain/bin/
      register: start_result
      ignore_errors: true

    - name: Server is Running 
      debug:
        msg: "Operation Successful! Please wait atleast 1 minute!"
      ignore_errors: true

