---

- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Start WebLogic
      shell: nohup /mwhome/obi/user_projects/domains/bifoundation_domain/bin/startWebLogic.sh > /dev/null 2>&1 &
      args:
        chdir: /mwhome/obi/user_projects/domains/bifoundation_domain/bin/
      register: start_result
      ignore_errors: true

    - name: Wait for the server to start
      pause:
        seconds: 60
      when: start_result.rc == 0  # Wait only if the start command was successful

    - name: Check if server is running
      command: tail -f nohup.out
      args:
        chdir: /mwhome/obi/user_projects/domains/bifoundation_domain/bin/
      ignore_errors: true
