---

- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Stop WebLogic
      shell: |
        cd /mwhome/obi/user_projects/domains/bifoundation_domain/bin
        ./stopWebLogic.sh
      register: stop_result
      ignore_errors: true

    - name: Display Stop WebLogic result
      debug:
        msg: "{{ stop_result.stdout }}"

